### ISSUE TITLE
No module named utils

### ISSUE THREAD

**Issue by lcl180** [Nihal987/Animal-Pose-Estimation#1]
When run  'python tools/dist_train.py \
    --cfg experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml', This error occurred：ModuleNotFoundError: No module named 'utils'

**Comment by Nihal987** [comment]
Ah yes I somehow missed the utils file, thanks for pointing this out. I've added it now

**Comment by lcl180** [comment]
Hello, I've been loading my own dataset with higherhrnet recently. I can't get through the code. Can I add your QQ&nbsp; to communicate?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nihal987/Animal-Pose-Estimation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nihal987/Animal-Pose-Estimation] No module named utils (Issue #1)





 
Ah yes I somehow missed the utils file, thanks for pointing this out. I've added it now
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
